import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import * as Scrollytelling from '@bsmnt/scrollytelling';

import { api } from "~/utils/api";

const CreatePostWizard = () => {
  const {user} = useUser();

  if (!user) return null;

  return (
  <div className="flex">
    <img src={user.imageUrl} alt="Profile Image"/>
  </div>
  )
}

export default function Home() {
  const user = useUser();
  const { data, isLoading} = api.post.getLatest.useQuery();

  if (isLoading) return <div>Loading...</div>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="h-full w-full border-b border-slate-400 md:max-w-2xl border-x">
          
          <div className="border-b borer-slate-400 p-4 flex">
            {!user.isSignedIn && (
            <div className="flex">
              <SignInButton />
            </div>
            )}
            {!!user.isSignedIn && <SignOutButton />}
          </div>
          <div className="flex flex-col">
            {data?.map((post) => (
            <div key={post.id} className="p-8 border-b border-slate-400">{post.content}</div>
            ))}
          </div>
        </div>
        <div>
          <Scrollytelling.Root>
            <div className="container">
              <Scrollytelling.Animation
                tween={{start: 0, end: 30, from: { opacity: 0, scale: 0.9} }}
              >
                <h1 className="title">Hello Sasha</h1>
              </Scrollytelling.Animation>
              <Scrollytelling.Animation
                tween={[
                  { start: 30, end: 80, to: { rotate: 360 }},
                  { start: 80, end: 100, to: { y: 100 }},
                ]}
              >
                <div className="box" />  
              </Scrollytelling.Animation>
            </div>
          </Scrollytelling.Root>
        </div>
      </main>
    </>
  );
}
