import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import * as Scrollytelling from '@bsmnt/scrollytelling';

import { api } from "~/utils/api";

const CreatePostWizard = () => {
  const {user} = useUser();

  if (!user) return null;

  return (
  <div className="flex">
    <img src={user.imageUrl} alt="Profile Image"/>
  </div>
  )
}

export default function Home() {
  const user = useUser();
  const { data, isLoading} = api.post.getLatest.useQuery();

  if (isLoading) return <div>Loading...</div>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="h-full w-full border-b border-slate-400 md:max-w-2xl border-x">
          
          <div className="border-b borer-slate-400 p-4 flex">
            {!user.isSignedIn && (
            <div className="flex">
              <SignInButton />
            </div>
            )}
            {!!user.isSignedIn && <SignOutButton />}
          </div>
          <div className="flex flex-col">
            {data?.map((post) => (
            <div key={post.id} className="p-8 border-b border-slate-400">{post.content}</div>
            ))}
          </div>

          <section className="section orange flex flex-col">
        <Scrollytelling.Root
          scrub={false}
          callbacks={{
            onEnterBack: (st) => {
              st.animation.seek(0).play();
            },
          }}
        >
          <div
            className="wrapper"
            style={{
              height: '100vh',
            }}
          >
            <Scrollytelling.Animation
              tween={{ start: 0, end: 1, to: { rotate: 360 } }}
            >
              <h1>This element will spin.</h1>
            </Scrollytelling.Animation>
          </div>
        </Scrollytelling.Root>
      </section>

      <section className="section flex flex-col">
        <Scrollytelling.Root scrub={false}>
          <div
            className="wrapper"
            style={{
              height: '100vh',
            }}
          >
            <Scrollytelling.Animation
              tween={{
                start: 0,
                end: 1,
                to: { scale: 1.5, yoyo: true, repeat: -1 },
              }}
            >
              <h1>Yoyo Text</h1>
            </Scrollytelling.Animation>
          </div>
        </Scrollytelling.Root>
      </section>
        </div>
      </main>
    </>
  );
}
